name: toxicity-remit-ci
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - pip:
      - --extra-index-url https://download.pytorch.org/whl/cpu
      - torch==2.11.0+cpu
      - -e .[dev]
